import subprocess
import unittest


SCRIPT = "scripts/verify-authority-object-admission-intake-reopening-request-future-snapshot-fork-ledger-non-terminal-closure-index-seal.sh"


class TestAuthorityObjectAdmissionIntakeReopeningRequestFutureSnapshotForkLedgerNonTerminalClosureIndexSeal(unittest.TestCase):
    def test_non_terminal_closure_index_seal(self):
        result = subprocess.run(["bash", SCRIPT], check=True, text=True, capture_output=True)
        out = result.stdout

        required = [
            "CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER NON-TERMINAL-CLOSURE-INDEX SEAL: PASS",
            "CURRENT_STATE=OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED",
            "NON_TERMINAL_CLOSURE_INDEX_SCOPE=CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY",
            "FUTURE_SNAPSHOT_FORK_LEDGER_NON_OUTSIDER_REPLAY_PASSAGE_SEALED=true",
            "FUTURE_SNAPSHOT_FORK_LEDGER_NON_TERMINAL_CLOSURE_INDEX_SEALED=true",
            "CURRENT_ZERO_LEDGER_TERMINAL_CLOSURE_INDEX_BLOCKED=true",
            "CURRENT_ZERO_LEDGER_TERMINAL_CLOSURE_INDEX_PRESENT=false",
            "CURRENT_ZERO_LEDGER_TERMINAL_CLOSURE_INDEX_SEALED=false",
            "TERMINAL_CLOSURE_INDEX_PRESENT=false",
            "TERMINAL_CLOSURE_INDEX_SEALED=false",
            "NON_OUTSIDER_REPLAY_PASSAGE_DOES_NOT_CREATE_TERMINAL_CLOSURE_INDEX=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_PASSED_FOR_FUTURE_FORK=false",
            "NON_TERMINAL_CLOSURE_INDEX_ARTIFACT_REQUIRED_FOR_FUTURE_FORK=true",
            "NON_TERMINAL_CLOSURE_INDEX_ARTIFACT_PRESENT_FOR_FUTURE_FORK=false",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_SATISFY_AUTHORITY=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_ADVANCE_STATE=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_ADMIT_MEDIA=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_PASS_OUTSIDER_REPLAY=true",
            "NON_TERMINAL_CLOSURE_INDEX_SEAL_DOES_NOT_SEAL_TERMINAL_CLOSURE_INDEX=true",
            "FUTURE_VALID_FORK_MUST_ESTABLISH_TERMINAL_CLOSURE_INDEX_INDEPENDENTLY=true",
            "FUTURE_VALID_FORK_TERMINAL_CLOSURE_INDEX_MUST_TARGET_NEW_SNAPSHOT=true",
            "OUTSIDER_REPLAY_PASSED=false",
            "AUTHORITY_SATISFIED=false",
            "MAY_ADVANCE_NOW=false",
            "RELEASE_CANDIDATE_READY=false",
            "ISSUED=false",
            "MEDIA_PRESENT=false",
        ]

        for item in required:
            self.assertIn(item, out)


if __name__ == "__main__":
    unittest.main()
