import subprocess
import unittest


SCRIPT = "scripts/verify-authority-object-admission-intake-reopening-request-future-snapshot-fork-ledger-non-outsider-replay-passage-seal.sh"


class TestAuthorityObjectAdmissionIntakeReopeningRequestFutureSnapshotForkLedgerNonOutsiderReplayPassageSeal(unittest.TestCase):
    def test_non_outsider_replay_passage_seal(self):
        result = subprocess.run(["bash", SCRIPT], check=True, text=True, capture_output=True)
        out = result.stdout

        required = ['CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER NON-OUTSIDER-REPLAY-PASSAGE SEAL: PASS', 'CURRENT_STATE=OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED', 'NON_OUTSIDER_REPLAY_PASSAGE_SCOPE=CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY', 'FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEALED=true', 'FUTURE_SNAPSHOT_FORK_LEDGER_NON_OUTSIDER_REPLAY_PASSAGE_SEALED=true', 'CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSAGE_BLOCKED=true', 'CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSED=false', 'NON_PROOF_ARTIFACT_DOES_NOT_CREATE_OUTSIDER_REPLAY_PASSAGE=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_PASSED_FOR_FUTURE_FORK=false', 'NON_OUTSIDER_REPLAY_PASSAGE_ARTIFACT_REQUIRED_FOR_FUTURE_FORK=true', 'NON_OUTSIDER_REPLAY_PASSAGE_ARTIFACT_PRESENT_FOR_FUTURE_FORK=false', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_SATISFY_AUTHORITY=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_ADVANCE_STATE=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_ADMIT_MEDIA=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT=true', 'NON_OUTSIDER_REPLAY_PASSAGE_SEAL_DOES_NOT_PASS_OUTSIDER_REPLAY=true', 'FUTURE_VALID_FORK_MUST_ESTABLISH_OUTSIDER_REPLAY_PASSAGE_INDEPENDENTLY=true', 'FUTURE_VALID_FORK_OUTSIDER_REPLAY_PASSAGE_MUST_TARGET_NEW_SNAPSHOT=true', 'OUTSIDER_REPLAY_PASSED=false', 'AUTHORITY_SATISFIED=false', 'MAY_ADVANCE_NOW=false', 'RELEASE_CANDIDATE_READY=false', 'ISSUED=false', 'MEDIA_PRESENT=false']

        for item in required:
            self.assertIn(item, out)


if __name__ == "__main__":
    unittest.main()
