#!/usr/bin/env bash
set -euo pipefail

STATUS="CASES/CASE_001_THE_LAST_RENDER/AUTHORITY_OBJECT_ADMISSION_INTAKE_REOPENING_REQUEST_FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEAL_STATUS.json"

python3 - <<'PY'
import json
from pathlib import Path

status = json.loads(Path("CASES/CASE_001_THE_LAST_RENDER/AUTHORITY_OBJECT_ADMISSION_INTAKE_REOPENING_REQUEST_FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEAL_STATUS.json").read_text())

required_true = [
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEALED",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_BLOCKED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "NON_MEDIA_ADMISSION_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_AUDIENCE_ARTIFACT_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_PROOF_ARTIFACT_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_PROOF_ARTIFACT_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_PROOF_ARTIFACT_INDEPENDENTLY",
    "FUTURE_VALID_FORK_PROOF_ARTIFACT_MUST_TARGET_NEW_SNAPSHOT",
]

required_false = [
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "NON_PROOF_ARTIFACT_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_PROOF_ARTIFACT_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
]

assert status["CURRENT_STATE"] == "OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED"
assert status["NON_PROOF_ARTIFACT_SCOPE"] == "CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY"
assert status["FUTURE_SNAPSHOT_FORK_RECORD_COUNT"] == 0
assert status["NEW_SNAPSHOT_RECORD_COUNT"] == 0

for key in required_true:
    assert status.get(key) is True, key
for key in required_false:
    assert status.get(key) is False, key

print("CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER NON-PROOF-ARTIFACT SEAL: PASS")
for key in [
    "CURRENT_STATE",
    "NON_PROOF_ARTIFACT_SCOPE",
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEALED",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_BLOCKED",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "FUTURE_SNAPSHOT_FORK_RECORD_COUNT",
    "NEW_SNAPSHOT_RECORD_COUNT",
    "NON_MEDIA_ADMISSION_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_AUDIENCE_ARTIFACT_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_PROOF_ARTIFACT_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_PROOF_ARTIFACT_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_PROOF_ARTIFACT_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_PROOF_ARTIFACT_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_PROOF_ARTIFACT_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_PROOF_ARTIFACT_INDEPENDENTLY",
    "FUTURE_VALID_FORK_PROOF_ARTIFACT_MUST_TARGET_NEW_SNAPSHOT",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
]:
    value = status[key]
    if isinstance(value, bool):
        value = str(value).lower()
    print(f"{key}={value}")
PY
