#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATUS="$ROOT/CASES/CASE_001_THE_LAST_RENDER/NON_STAR_SEAL_REDUNDANCY_STOP_RULE_STATUS.json"
OBJECT="$ROOT/CINEMATICUM_NON_STAR_SEAL_REDUNDANCY_STOP_RULE.json"
LAW="$ROOT/CINEMATICUM_NON_STAR_SEAL_REDUNDANCY_STOP_RULE_LAW.json"

python3 - "$STATUS" "$OBJECT" "$LAW" <<'PY'
import json
import sys
from pathlib import Path

status = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
obj = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
law = json.loads(Path(sys.argv[3]).read_text(encoding="utf-8"))

true_keys = [
    "ZERO_PERIMETER_COMPLETION_INDEX_PRESENT",
    "ZERO_PERIMETER_COMPLETION_INDEX_SEALED",
    "CURRENT_ZERO_LEDGER_NEGATIVE_PERIMETER_COMPLETE",
    "CURRENT_ZERO_LEDGER_CLOSED_AGAINST_RECLASSIFICATION",
    "NON_STAR_SEAL_REDUNDANCY_STOP_RULE_PRESENT",
    "NON_STAR_SEAL_REDUNDANCY_STOP_RULE_SEALED",
    "ADDITIONAL_NON_STAR_SEAL_DEFAULT_FORBIDDEN",
    "ADDITIONAL_NON_STAR_SEAL_ALLOWED_ONLY_IF_REQUIRED_TO_UNBLOCK_REAL_INTAKE",
    "ADDITIONAL_NON_STAR_SEAL_MUST_NAME_UNBLOCKED_REAL_INTAKE_GATE",
    "ADDITIONAL_NON_STAR_SEAL_MUST_NOT_RECLASSIFY_CURRENT_ZERO_LEDGER",
    "ADDITIONAL_NON_STAR_SEAL_MUST_NOT_DELAY_REAL_CASE_AUTHORITY_INTAKE",
    "FUTURE_WORK_MUST_ROUTE_TO_REAL_CASE_AUTHORITY_INTAKE",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "STOP_RULE_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "STOP_RULE_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "STOP_RULE_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "STOP_RULE_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "STOP_RULE_DOES_NOT_SATISFY_AUTHORITY",
    "STOP_RULE_DOES_NOT_ADVANCE_STATE",
    "STOP_RULE_DOES_NOT_ISSUE_MOTION_PICTURE",
    "STOP_RULE_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "STOP_RULE_DOES_NOT_ADMIT_MEDIA",
    "STOP_RULE_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "STOP_RULE_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "STOP_RULE_DOES_NOT_PASS_OUTSIDER_REPLAY",
    "STOP_RULE_DOES_NOT_SEAL_TERMINAL_CLOSURE_INDEX",
    "STOP_RULE_DOES_NOT_SEAL_PUBLIC_REPLAY_INDEX",
    "STOP_RULE_DOES_NOT_SEAL_PUBLIC_INSPECTION_VERDICT",
]
false_keys = [
    "CURRENT_ZERO_LEDGER_FURTHER_NON_CAPABILITY_SEALS_REQUIRED",
    "RULE_CREATES_NON_STAR_SEAL_ARTIFACT",
    "RULE_CREATES_CAPABILITY_SEAL_ARTIFACT",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSED",
    "CURRENT_ZERO_LEDGER_TERMINAL_CLOSURE_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_INSPECTION_VERDICT_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
    "OUTSIDER_REPLAY_PASSED",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
]
for key in true_keys:
    assert status[key] is True, key
for key in false_keys:
    assert status[key] is False, key

assert status["CURRENT_STATE"] == "REAL_CASE_AUTHORITY_OBJECTS_INSTANTIATED_PENDING_RELEASE_CANDIDATE_ARTIFACTS", status["CURRENT_STATE"]
assert status["RULE_SCOPE"] == "POST_ZERO_PERIMETER_CURRENT_MAIN_ONLY"
assert status["NEXT_REQUIRED_PHASE"] == "REAL_CASE_AUTHORITY_INTAKE"
assert status["NEXT_REQUIRED_OBJECT"] == "CURRENT_ZERO_LEDGER_NO_FURTHER_ADVANCEMENT_PROOF"
assert status["TRANSITION_REQUEST_OBJECT"] == "OPEN_REAL_CASE_AUTHORITY_INTAKE"
assert status["FUTURE_SNAPSHOT_FORK_RECORD_COUNT"] == 0
assert status["NEW_SNAPSHOT_RECORD_COUNT"] == 0

assert obj["object_type"] == "NON_STAR_SEAL_REDUNDANCY_STOP_RULE"
assert obj["canonical_rule_name"] == "NON_*_SEAL_REDUNDANCY_STOP_RULE"
assert obj["creates_non_star_seal"] is False
assert obj["future_work_must_route_to_real_case_authority_intake"] is True

assert law["canonical_rule_name"] == "NON_*_SEAL_REDUNDANCY_STOP_RULE"
assert law["redundancy_rule"]["additional_non_star_seal_default_forbidden"] is True
assert law["non_redundant_next_route"]["next_object_after_stop_rule"] == "CURRENT_ZERO_LEDGER_NO_FURTHER_ADVANCEMENT_PROOF"
assert "create_non_star_seal_artifact" in law["forbidden_effects"]
PY

printf "CINEMATICUM NON_* SEAL REDUNDANCY STOP RULE: PASS\n"
printf "CURRENT_STATE=REAL_CASE_AUTHORITY_OBJECTS_INSTANTIATED_PENDING_RELEASE_CANDIDATE_ARTIFACTS\n"
printf "RULE_SCOPE=POST_ZERO_PERIMETER_CURRENT_MAIN_ONLY\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_PRESENT=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_SEALED=true\n"
printf "CURRENT_ZERO_LEDGER_NEGATIVE_PERIMETER_COMPLETE=true\n"
printf "CURRENT_ZERO_LEDGER_FURTHER_NON_CAPABILITY_SEALS_REQUIRED=false\n"
printf "NON_STAR_SEAL_REDUNDANCY_STOP_RULE_PRESENT=true\n"
printf "NON_STAR_SEAL_REDUNDANCY_STOP_RULE_SEALED=true\n"
printf "RULE_CREATES_NON_STAR_SEAL_ARTIFACT=false\n"
printf "ADDITIONAL_NON_STAR_SEAL_DEFAULT_FORBIDDEN=true\n"
printf "ADDITIONAL_NON_STAR_SEAL_ALLOWED_ONLY_IF_REQUIRED_TO_UNBLOCK_REAL_INTAKE=true\n"
printf "FUTURE_WORK_MUST_ROUTE_TO_REAL_CASE_AUTHORITY_INTAKE=true\n"
printf "NEXT_REQUIRED_OBJECT=CURRENT_ZERO_LEDGER_NO_FURTHER_ADVANCEMENT_PROOF\n"
printf "TRANSITION_REQUEST_OBJECT=OPEN_REAL_CASE_AUTHORITY_INTAKE\n"
printf "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW=false\n"
printf "NEW_SNAPSHOT_RECORD_COUNT=0\n"
printf "STOP_RULE_DOES_NOT_ADVANCE_STATE=true\n"
printf "STOP_RULE_DOES_NOT_ISSUE_MOTION_PICTURE=true\n"
printf "AUTHORITY_SATISFIED=false\n"
printf "MAY_ADVANCE_NOW=false\n"
printf "RELEASE_CANDIDATE_READY=false\n"
printf "ISSUED=false\n"
printf "MEDIA_PRESENT=false\n"
