#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATUS="$ROOT/CASES/CASE_001_THE_LAST_RENDER/AUTHORITY_OBJECT_ADMISSION_INTAKE_REOPENING_REQUEST_FUTURE_SNAPSHOT_FORK_LEDGER_ZERO_PERIMETER_COMPLETION_INDEX_STATUS.json"

python3 - "$STATUS" <<'PY'
import json
import sys
from pathlib import Path

status = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))

true_keys = [
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_OUTSIDER_REPLAY_PASSAGE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_TERMINAL_CLOSURE_INDEX_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PUBLIC_REPLAY_INDEX_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PUBLIC_INSPECTION_VERDICT_SEALED",
    "CURRENT_ZERO_LEDGER_NEGATIVE_PERIMETER_COMPLETE",
    "CURRENT_ZERO_LEDGER_CLOSED_AGAINST_RECLASSIFICATION",
    "ZERO_PERIMETER_COMPLETION_INDEX_PRESENT",
    "ZERO_PERIMETER_COMPLETION_INDEX_SEALED",
    "FUTURE_WORK_MUST_ROUTE_TO_REAL_CASE_AUTHORITY_INTAKE",
    "ADDITIONAL_NEGATIVE_SEAL_DEFAULT_FORBIDDEN",
    "ADDITIONAL_NEGATIVE_SEAL_ALLOWED_ONLY_IF_REQUIRED_TO_UNBLOCK_REAL_INTAKE",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_SATISFY_AUTHORITY",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ADVANCE_STATE",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ISSUE_MOTION_PICTURE",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ADMIT_MEDIA",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_PASS_OUTSIDER_REPLAY",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_SEAL_TERMINAL_CLOSURE_INDEX",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_SEAL_PUBLIC_REPLAY_INDEX",
    "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_SEAL_PUBLIC_INSPECTION_VERDICT",
]
false_keys = [
    "CURRENT_ZERO_LEDGER_FURTHER_NON_CAPABILITY_SEALS_REQUIRED",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSED",
    "CURRENT_ZERO_LEDGER_TERMINAL_CLOSURE_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_INSPECTION_VERDICT_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
    "OUTSIDER_REPLAY_PASSED",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
]
for key in true_keys:
    assert status[key] is True, key
for key in false_keys:
    assert status[key] is False, key
assert status["CURRENT_STATE"] == "OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED"
assert status["NEXT_REQUIRED_PHASE"] == "REAL_CASE_AUTHORITY_INTAKE"
assert status["NEXT_REQUIRED_OBJECT"] == "OPEN_REAL_CASE_AUTHORITY_INTAKE"
assert status["FUTURE_SNAPSHOT_FORK_RECORD_COUNT"] == 0
assert status["NEW_SNAPSHOT_RECORD_COUNT"] == 0
PY

printf "CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER ZERO PERIMETER COMPLETION INDEX: PASS\n"
printf "CURRENT_STATE=OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_SCOPE=CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY\n"
printf "CURRENT_ZERO_LEDGER_NEGATIVE_PERIMETER_COMPLETE=true\n"
printf "CURRENT_ZERO_LEDGER_FURTHER_NON_CAPABILITY_SEALS_REQUIRED=false\n"
printf "CURRENT_ZERO_LEDGER_CLOSED_AGAINST_RECLASSIFICATION=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_PRESENT=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_SEALED=true\n"
printf "FUTURE_WORK_MUST_ROUTE_TO_REAL_CASE_AUTHORITY_INTAKE=true\n"
printf "NEXT_REQUIRED_PHASE=REAL_CASE_AUTHORITY_INTAKE\n"
printf "NEXT_REQUIRED_OBJECT=OPEN_REAL_CASE_AUTHORITY_INTAKE\n"
printf "ADDITIONAL_NEGATIVE_SEAL_DEFAULT_FORBIDDEN=true\n"
printf "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW=false\n"
printf "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW=false\n"
printf "FUTURE_SNAPSHOT_FORK_RECORD_COUNT=0\n"
printf "NEW_SNAPSHOT_RECORD_COUNT=0\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_OPEN_FUTURE_FORK_GATE=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_CREATE_NEW_SNAPSHOT=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_MUTATE_CURRENT_SNAPSHOT=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_SATISFY_AUTHORITY=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ADVANCE_STATE=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ISSUE_MOTION_PICTURE=true\n"
printf "ZERO_PERIMETER_COMPLETION_INDEX_DOES_NOT_ADMIT_MEDIA=true\n"
printf "AUTHORITY_SATISFIED=false\n"
printf "MAY_ADVANCE_NOW=false\n"
printf "RELEASE_CANDIDATE_READY=false\n"
printf "ISSUED=false\n"
printf "MEDIA_PRESENT=false\n"
