#!/usr/bin/env bash
set -euo pipefail

python3 - <<'PY'
import json
from pathlib import Path

UPPER = "AUTHORITY_OBJECT_ADMISSION_INTAKE_REOPENING_REQUEST_FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEAL"
CASE_DIR = Path("CASES/CASE_001_THE_LAST_RENDER")

paths = {
    "status": CASE_DIR / f"{UPPER}_STATUS.json",
    "object": Path(f"CINEMATICUM_{UPPER}.json"),
    "law": Path(f"CINEMATICUM_{UPPER}_LAW.json"),
}

for label, path in paths.items():
    assert path.exists(), f"missing {label}: {path}"

docs = {label: json.loads(path.read_text()) for label, path in paths.items()}
status = docs["status"]

required_true = [
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_BLOCKED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "NON_MEDIA_ADMISSION_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_AUDIENCE_ARTIFACT_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_AUDIENCE_ARTIFACT_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_AUDIENCE_ARTIFACT_INDEPENDENTLY",
    "FUTURE_VALID_FORK_AUDIENCE_ARTIFACT_MUST_TARGET_NEW_SNAPSHOT",
]

required_false = [
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "NON_AUDIENCE_ARTIFACT_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_AUDIENCE_ARTIFACT_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
]

required_zero = [
    "FUTURE_SNAPSHOT_FORK_RECORD_COUNT",
    "NEW_SNAPSHOT_RECORD_COUNT",
]

for label, doc in docs.items():
    assert doc.get("CURRENT_STATE") == "OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED", label
    assert doc.get("NON_AUDIENCE_ARTIFACT_SCOPE") == "CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY", label

    for key in required_true:
        assert doc.get(key) is True, f"{label}:{key} expected true got {doc.get(key)!r}"

    for key in required_false:
        assert doc.get(key) is False, f"{label}:{key} expected false got {doc.get(key)!r}"

    for key in required_zero:
        assert doc.get(key) == 0, f"{label}:{key} expected 0 got {doc.get(key)!r}"

print("CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER NON-AUDIENCE-ARTIFACT SEAL: PASS")
for key in [
    "CURRENT_STATE",
    "NON_AUDIENCE_ARTIFACT_SCOPE",
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_BLOCKED",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "FUTURE_SNAPSHOT_FORK_RECORD_COUNT",
    "NEW_SNAPSHOT_RECORD_COUNT",
    "NON_MEDIA_ADMISSION_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_AUDIENCE_ARTIFACT_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_AUDIENCE_ARTIFACT_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_AUDIENCE_ARTIFACT_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_AUDIENCE_ARTIFACT_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_AUDIENCE_ARTIFACT_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_AUDIENCE_ARTIFACT_INDEPENDENTLY",
    "FUTURE_VALID_FORK_AUDIENCE_ARTIFACT_MUST_TARGET_NEW_SNAPSHOT",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
]:
    print(f"{key}={str(status.get(key)).lower() if isinstance(status.get(key), bool) else status.get(key)}")
PY
