#!/usr/bin/env bash
set -euo pipefail
python3 - <<'PY2'
import json
from pathlib import Path

root = Path(".")
obj = "RELEASE_CANDIDATE_READY_ISSUANCE_UNBLOCKING_DECISION_RECORD"
r = json.loads((root / f"{obj}.json").read_text())
c = json.loads((root / "CASES/CASE_001_THE_LAST_RENDER" / f"{obj}_STATUS.json").read_text())

assert r["CURRENT_STATE"] == "RELEASE_CANDIDATE_READY"
assert r["DECISION_OBJECT"] == obj
assert r["DECISION_ID"] == "DEC_001_RELEASE_CANDIDATE_READY_ISSUANCE_UNBLOCKING"
assert r["REQUEST_OBJECT"] == "RELEASE_CANDIDATE_READY_ISSUANCE_UNBLOCKING_REQUEST"
assert r["REQUEST_ID"] == "REQ_001_RELEASE_CANDIDATE_READY_ISSUANCE_UNBLOCKING_REQUEST"
assert r["REQUIRED_PRIOR_OBJECT"] == "RELEASE_CANDIDATE_READY_ISSUANCE_BLOCKADE_SEAL"
assert r["NEXT_REQUIRED_OBJECT"] == "RELEASE_CANDIDATE_READY_ISSUANCE_UNBLOCKING_EXECUTION_RECORD"

for k in [
    "RELEASE_CANDIDATE_READY",
    "BLOCKADE_SEAL_PRESENT",
    "ISSUANCE_UNBLOCKING_REQUEST_PRESENT",
    "DECISION_RECORD_PRESENT",
    "DECISION_ACCEPTS_REQUEST",
    "DECISION_AUTHORIZES_ISSUANCE_UNBLOCKING",
    "ISSUANCE_UNBLOCKING_EXECUTION_RECORD_REQUIRED_BEFORE_UNBLOCKING",
    "DECISION_DOES_NOT_UNBLOCK_ISSUANCE",
    "DECISION_DOES_NOT_ISSUE_MOTION_PICTURE",
    "DECISION_DOES_NOT_ADMIT_MEDIA",
    "CURRENT_STATE_UNCHANGED",
]:
    assert r[k] is True, k

for k in ["MAY_ADVANCE_NOW", "ISSUANCE_UNBLOCKED", "ISSUED", "MEDIA_PRESENT"]:
    assert r[k] is False, k
    assert c[k] is False, "case:" + k

print("CINEMATICUM RELEASE CANDIDATE READY ISSUANCE UNBLOCKING DECISION RECORD: PASS")
for k in [
    "CURRENT_STATE", "DECISION_SCOPE", "DECISION_OBJECT", "DECISION_ID",
    "REQUEST_OBJECT", "REQUEST_ID", "REQUESTED_NEXT_STATE",
    "REQUIRED_PRIOR_OBJECT", "RELEASE_CANDIDATE_READY",
    "BLOCKADE_SEAL_PRESENT", "ISSUANCE_UNBLOCKING_REQUEST_PRESENT",
    "DECISION_RECORD_PRESENT", "DECISION_ACCEPTS_REQUEST",
    "DECISION_AUTHORIZES_ISSUANCE_UNBLOCKING",
    "ISSUANCE_UNBLOCKING_EXECUTION_RECORD_REQUIRED_BEFORE_UNBLOCKING",
    "DECISION_DOES_NOT_UNBLOCK_ISSUANCE", "MAY_ADVANCE_NOW",
    "ISSUANCE_UNBLOCKED", "ISSUED", "MEDIA_PRESENT",
    "CURRENT_STATE_UNCHANGED", "NEXT_REQUIRED_OBJECT"
]:
    v = r[k]
    print(f"{k}={str(v).lower() if isinstance(v, bool) else v}")
PY2
