#!/usr/bin/env bash
set -euo pipefail

python3 - <<'PY2'
import json
from pathlib import Path

status = json.loads(Path("CASES/CASE_001_THE_LAST_RENDER/AUTHORITY_OBJECT_ADMISSION_INTAKE_REOPENING_REQUEST_FUTURE_SNAPSHOT_FORK_LEDGER_NON_PUBLIC_REPLAY_INDEX_SEAL_STATUS.json").read_text(encoding="utf-8"))

required_true = [
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ISSUANCE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUTHORITY_SATISFACTION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_ADVANCEMENT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_RELEASE_CANDIDATE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_MEDIA_ADMISSION_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_AUDIENCE_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PROOF_ARTIFACT_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_OUTSIDER_REPLAY_PASSAGE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_TERMINAL_CLOSURE_INDEX_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PUBLIC_REPLAY_INDEX_SEALED",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_BLOCKED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "NON_TERMINAL_CLOSURE_INDEX_DOES_NOT_CREATE_PUBLIC_REPLAY_INDEX",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_PUBLIC_REPLAY_INDEX_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_PASS_OUTSIDER_REPLAY",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_SEAL_PUBLIC_REPLAY_INDEX",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_PUBLIC_REPLAY_INDEX_INDEPENDENTLY",
    "FUTURE_VALID_FORK_PUBLIC_REPLAY_INDEX_MUST_TARGET_NEW_SNAPSHOT",
]
required_false = [
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_PUBLIC_REPLAY_INDEX_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_SEALED",
    "PUBLIC_REPLAY_INDEX_PRESENT",
    "PUBLIC_REPLAY_INDEX_SEALED",
    "CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSED",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
    "OUTSIDER_REPLAY_PASSED",
]

assert status["CURRENT_STATE"] == "OUTSIDER_REPLAY_BUNDLE_LAW_DECLARED"
assert status["NON_PUBLIC_REPLAY_INDEX_SCOPE"] == "CURRENT_ZERO_FUTURE_SNAPSHOT_FORK_LEDGER_ONLY"
assert status["FUTURE_SNAPSHOT_FORK_RECORD_COUNT"] == 0
assert status["NEW_SNAPSHOT_RECORD_COUNT"] == 0

for key in required_true:
    assert status.get(key) is True, key
for key in required_false:
    assert status.get(key) is False, key

print("CINEMATICUM AUTHORITY OBJECT ADMISSION INTAKE REOPENING REQUEST FUTURE SNAPSHOT FORK LEDGER NON-PUBLIC-REPLAY-INDEX SEAL: PASS")
for key in [
    "CURRENT_STATE",
    "NON_PUBLIC_REPLAY_INDEX_SCOPE",
    "FUTURE_SNAPSHOT_FORK_LEDGER_PRESENT",
    "FUTURE_SNAPSHOT_FORK_LEDGER_TERMINAL_CLOSURE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_OUTSIDER_REPLAY_PASSAGE_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_TERMINAL_CLOSURE_INDEX_SEALED",
    "FUTURE_SNAPSHOT_FORK_LEDGER_NON_PUBLIC_REPLAY_INDEX_SEALED",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_BLOCKED",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_PRESENT",
    "CURRENT_ZERO_LEDGER_PUBLIC_REPLAY_INDEX_SEALED",
    "PUBLIC_REPLAY_INDEX_PRESENT",
    "PUBLIC_REPLAY_INDEX_SEALED",
    "CURRENT_ZERO_LEDGER_OUTSIDER_REPLAY_PASSED",
    "CURRENT_ZERO_LEDGER_PROOF_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_AUDIENCE_ARTIFACT_PRESENT",
    "CURRENT_ZERO_LEDGER_MEDIA_PRESENT",
    "CURRENT_ZERO_LEDGER_RELEASE_CANDIDATE_READY",
    "CURRENT_ZERO_LEDGER_MAY_ADVANCE_NOW",
    "CURRENT_ZERO_LEDGER_AUTHORITY_SATISFIED",
    "CURRENT_ZERO_LEDGER_ISSUED",
    "CURRENT_ZERO_LEDGER_STATE_UNCHANGED",
    "FUTURE_SNAPSHOT_FORK_GATE_PASSED_NOW",
    "FUTURE_SNAPSHOT_FORK_GATE_OPEN_NOW",
    "FUTURE_SNAPSHOT_FORK_RECORD_COUNT",
    "NEW_SNAPSHOT_RECORD_COUNT",
    "NON_TERMINAL_CLOSURE_INDEX_DOES_NOT_CREATE_PUBLIC_REPLAY_INDEX",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_PASSED_FOR_CURRENT_ZERO_LEDGER",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_PASSED_FOR_FUTURE_FORK",
    "NON_PUBLIC_REPLAY_INDEX_ARTIFACT_REQUIRED_FOR_FUTURE_FORK",
    "NON_PUBLIC_REPLAY_INDEX_ARTIFACT_PRESENT_FOR_FUTURE_FORK",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_OPEN_FUTURE_FORK_GATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_NEW_SNAPSHOT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_MUTATE_CURRENT_SNAPSHOT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_MUTATE_PERMANENT_LEDGER",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_SATISFY_AUTHORITY",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ADVANCE_STATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ISSUE_MOTION_PICTURE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_RELEASE_CANDIDATE",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_ADMIT_MEDIA",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_AUDIENCE_ARTIFACT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_CREATE_PROOF_ARTIFACT",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_PASS_OUTSIDER_REPLAY",
    "NON_PUBLIC_REPLAY_INDEX_SEAL_DOES_NOT_SEAL_PUBLIC_REPLAY_INDEX",
    "FUTURE_VALID_FORK_MUST_ESTABLISH_PUBLIC_REPLAY_INDEX_INDEPENDENTLY",
    "FUTURE_VALID_FORK_PUBLIC_REPLAY_INDEX_MUST_TARGET_NEW_SNAPSHOT",
    "PRIVATE_ACCESS_REQUIRED",
    "NETWORK_REQUIRED_AFTER_CLONE",
    "MEDIA_OR_MODEL_PAYLOAD_PRESENT",
    "AUTHORITY_SATISFIED",
    "MAY_ADVANCE_NOW",
    "RELEASE_CANDIDATE_READY",
    "ISSUED",
    "MEDIA_PRESENT",
    "AUDIENCE_ARTIFACT_PRESENT",
    "PROOF_ARTIFACT_PRESENT",
    "OUTSIDER_REPLAY_PASSED",
]:
    value = status[key]
    if isinstance(value, bool):
        value = str(value).lower()
    print(f"{key}={value}")
PY2
